name: "Github mention to Slack"
description: "Convert Github mention to Slack mention"
inputs:
  slack-webhook-url:
    description: "Slack Incomming Webhook URL to notify."
    required: true
  bot-name:
    description: "Display name for this bot on Slack."
    required: false
  icon-url:
    description: "Display icon url for this bot on Slack."
    required: false
runs:
  using: "node12"
  main: "dist/index.js"
branding:
  icon: "message-square"
  color: "red"
