name: Slack Mention

on:
  issues:
    types: [opened]
  issue_comment:
    types: [created]
  pull_request:
    types: [opened, review_requested]
  pull_request_review:
    types: [submitted]
  pull_request_review_comment:
    types: [created]

jobs:
  mention-to-slack:
    runs-on: ubuntu-latest
    steps:
      - name: Run
        uses: infinitecsolutions/actions-digibank-mention-to-slack@v3.0.1
        with:
          slack-webhook-url: ${{ secrets.SLACK_WEBHOOK_URL }}
